### ISSUE TITLE
Speed up tt-flash by multi-threading on each PCI device

### ISSUE THREAD

**Issue by hmohiuddinTT** [tenstorrent/tt-flash#11]
Each individual PCIe device (and it's accompanying remote chip for n300s) can be flashed concurrently. We can speed up the current process up-to 8x by creating a thread per PCIe device and flashing in parallel.

**Comment by warthog9** [comment]
Arguably related to #12

**Comment by hmohiuddinTT** [comment]
I think the fix to #12 would eliminate the intermediate waits and just wait once at the end but doesn't multi-thread flashing individual PCIe devices. @TTDRosen thoughts on this?

**Comment by hmohiuddinTT** [comment]
Issue is resolved in v2.1.0
