### ISSUE TITLE
Flashing n300 boards is too slow because of unnecessary wait

### ISSUE THREAD

**Issue by hmohiuddinTT** [tenstorrent/tt-flash#12]
After flashing each remote chip we wait for 15 seconds to do the LtoR copy but this is unnecessary if we're flashing multiple boards. Can we instead just wait once at the end after all the chips have been flashed?

Also can we revert back to doing the LtoR copy only when necessary? Or is this needed for safety reasons to prevent any issues with half-flashed boards?

**Comment by TTDRosen** [comment]
Should be fixed as of v2.10, will now run the 15 second wait one time for any number of n300s.

**Comment by hmohiuddinTT** [comment]
Issue is resolved in v2.1.0
