### ISSUE TITLE
Detect if M3 APP FW get's updated and display message to reboot twice

### ISSUE THREAD

**Issue by hmohiuddinTT** [tenstorrent/tt-flash#5]
Any time the M3 App FW gets updated, a host reboot will cause the boards to not enumerate and a second reboot is needed.

TT-Flash should display a smart message to the user to indicate if 2 reboots are needed if M3 gets updated.

**Comment by TTDRosen** [comment]
I forgot to update here, I have this feature added but enablement is pending on some larger scale process improvements which we are currently working on.

**Comment by TTDRosen** [comment]
This should now be fixed as of v2.1.0

**Comment by hmohiuddinTT** [comment]
Thanks Daniel, will check if this is resolved.

**Comment by changh95** [comment]
This doesn't seem fixed - just encountered this error and had to reboot twice to flash the new n300 card.
